Jpmobile::Mobile::Emobile::DEVICE_INFO = 
{"H11T"=>
  {:flash=>true,
   :flash_version=>"2.0",
   :ssl=>false,
   :name=>"H11T",
   :css=>true,
   :gif=>true,
   :gps=>false,
   :jpg=>true,
   :png=>true}}
